source 'https://rubygems.org'

gem 'sinatra'
gem 'activemodel-serializers-xml'
gem 'active_model_serializers'
gem 'serialport'
gem 'httparty'
gem 'bson_ext'
gem 'pry-byebug'
gem 'time_difference'
gem 'mongo'
